package com.bankbis.ui;

import com.bankbis.optimizer.Loadout;
import com.duckblade.osrs.dpscalc.calc.model.ItemStats;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;
import java.util.Map;
import net.runelite.api.EquipmentInventorySlot;
import net.runelite.client.ui.ColorScheme;
import net.runelite.client.util.Text;

/**
 * Builds the Inventory Setups plugin's portable JSON for a loadout, so a
 * recommendation can be pasted straight into its "Import setup" action.
 * Format: {"setup": InventorySetupSerializable} - short field names, 28/14
 * fixed-size item arrays indexed by container slot, empty slots as null,
 * layout omitted (the plugin regenerates it on import).
 */
final class InventorySetupExport
{

	private static final int NUM_INVENTORY_ITEMS = 28;
	private static final int NUM_EQUIPMENT_ITEMS = 14;

	private InventorySetupExport()
	{
	}

	static String toJson(Gson gson, Loadout loadout, String targetLabel)
	{
		JsonArray inv = new JsonArray();
		for (int i = 0; i < NUM_INVENTORY_ITEMS; i++)
		{
			inv.add(JsonNull.INSTANCE);
		}

		ItemStats[] bySlot = new ItemStats[NUM_EQUIPMENT_ITEMS];
		for (Map.Entry<EquipmentInventorySlot, ItemStats> entry : loadout.getItems().entrySet())
		{
			int idx = entry.getKey().getSlotIdx();
			if (idx >= 0 && idx < NUM_EQUIPMENT_ITEMS)
			{
				bySlot[idx] = entry.getValue();
			}
		}
		JsonArray eq = new JsonArray();
		for (int i = 0; i < NUM_EQUIPMENT_ITEMS; i++)
		{
			if (bySlot[i] == null)
			{
				eq.add(JsonNull.INSTANCE);
				continue;
			}
			JsonObject item = new JsonObject();
			item.addProperty("id", bySlot[i].getItemId());
			item.addProperty("q", 1);
			eq.add(item);
		}

		JsonObject setup = new JsonObject();
		setup.add("inv", inv);
		setup.add("eq", eq);
		setup.addProperty("name", targetLabel + " - " + Text.titleCase(loadout.getCombatClass()));
		setup.addProperty("notes", String.format("Generated by Banked BiS: %.2f DPS vs %s.",
			loadout.getDps(), targetLabel));
		JsonObject highlightColor = new JsonObject();
		highlightColor.addProperty("value", ColorScheme.BRAND_ORANGE.getRGB());
		setup.add("hc", highlightColor);

		// the import path requires a non-null bank-tab layout (item id per
		// slot, -1 empty, 8 per row); lay the gear out in display order
		JsonArray layout = new JsonArray();
		for (int i = 0; i < NUM_EQUIPMENT_ITEMS; i++)
		{
			if (bySlot[i] != null)
			{
				layout.add(bySlot[i].getItemId());
			}
		}
		while (layout.size() % 8 != 0)
		{
			layout.add(-1);
		}

		JsonObject root = new JsonObject();
		root.add("setup", setup);
		root.add("layout", layout);
		return gson.toJson(root);
	}

}
